Attribute VB_Name = "modNSLookupImport"
Option Compare Database

Sub TxtImport()
    'Script used to import files from NSLookup - this is after the batch file is run
    'The script asks for the directory of the files and then generates a final Results file
    'The Results file is then loaded into a database table

    Dim strPath As String
    Dim strFile As String
    Dim strFilePath As String
    Dim header As String
    Dim entry As String
    Dim trigger As String
    Dim deviceName As String
    Dim ipAddress As String
    Dim bogusFile As String
    
    strPath = Get_Directory("Choose the folder with the files for import") & "\"    'Call the Get_Directory function for the file path
                                                                                    'A \ is also appended to the file path so it can be used later

    'Remove the resultFile from a previous run of this script
    resultFile = "C:\Scripts\Results.txt"
    Open resultFile For Append As #9
    Close #9
    Kill resultFile
    
    'Remove bogus Aud_NS file that is generated by the batch script
    bogusFile = strPath + "Aud_NS_list_.txt"
    Open bogusFile For Append As #99
    Close #99
    Kill bogusFile
    
    strFile = Dir(strPath & "*.txt")    'Get the first file in the path
    
    While strFile <> ""                 'While there are still files to process the loop will continue
        header = Mid(strFile, 13, Len(strFile) - (InStr(strFile, ".") - 4))     'Get the header from the file name to know which ID is being reviewed
        strFilePath = strPath + strFile
        Open strFilePath For Input As #1    'Open the text file
        Do Until EOF(1)
            Input #1, entry
            trigger = Mid(entry, 1, 4)
            If trigger = "Name" Then        'Review text in the file to find the Name field which represents name of the device
                deviceName = Mid(entry, 10, Len(entry) - 9)     'Populate the deviceName variable with the name of the device
            End If
            If deviceName <> "" Then        'Once you have a device name you can look for the IP Address - this can only be done after a device name is populated
                If trigger = "Addr" Then
                    ipAddress = Mid(entry, 10, Len(entry) - 9)
                End If
            End If
        Loop
        
        'Open the resultFile and poplate the header, device name and IP into the text file
        Open resultFile For Append As #9
        Write #9, header, deviceName, ipAddress
        Close #9
        
        'Reset the device and IP address variables to NULL
        deviceName = ""
        ipAddress = ""
        Close #1        'Close the text file
        strFile = Dir() 'Pull the next file in the path
    Wend
    
    Dim strTableName As String
    Dim fileDate As String
    
    'fileDate = TodayDate()
    
    'Remove previous version of this file if it was run earlier in the dat
    'It now has a date stamp included with the file name
    
    strTableName = "NSLookupResults" + fileDate
    If TableExists(strTableName) Then
        DoCmd.DeleteObject acTable, strTableName
    End If
    
    'Import the text file into a database table
    DoCmd.TransferText acImportDelim, , strTableName, resultFile, False
    
    Application.RefreshDatabaseWindow
    

End Sub
